export const testIds = {
  searchInputField: "searchInputField",
  rpcIssueDialog: "rpcIssueDialog",
  connectionStatusReport: "connectionStatusReport",
  unauthorizedMessage: "unauthorizedMessage",
  rpcSettingsInDialog: "rpcSettingsInDialog",
  rpcSettingsSaveButton: "rpcSettingsSaveButton",
  enterServerDetails: "enterServerDetails",
  setCookiePathFromDialog: "setCookiePathFromDialog",
  useCookieAuthentication: "useCookieAuthentication",
  rpcSettingsFromCookiePath: "rpcSettingsFromCookiePath",
  rpcSettingsFormUsername: "rpcSettingsFormUsername",
  rpcSettingsFormPassword: "rpcSettingsFormPassword",
  rpcSettingsFormServerUrl: "rpcSettingsFormServerUrl",
  connectionStatusReportCloseButton: "connectionStatusReportCloseButton",
  useDefaultSettings: "useDefaultSettings",
  blockListBlock: "blockListBlock",
  scrollableBlockContainer: "scrollableBlockContainer",
  settingsPage: "settingsPage",
  settingsButton: "settingsButton",
  settingsSavedSnackBar: "settingsSavedSnackBar",
  homeButton: "homeButton",
  explorerPage: "explorerPage",
  transactionDetails: "transactionDetails",
} as const;
