const keyEqualsValue = <T extends { [P in keyof T]: P }>(o: T) => o;

export const testIds = keyEqualsValue({
  depthBottomLinkSearchButton: "depthBottomLinkSearchButton",
  depthBottomLink: "depthBottomLink",
  searchInputField: "searchInputField",
  rpcIssueDialog: "rpcIssueDialog",
  connectionStatusReport: "connectionStatusReport",
  unauthorizedMessage: "unauthorizedMessage",
  rpcSettingsInDialog: "rpcSettingsInDialog",
  rpcSettingsSaveButton: "rpcSettingsSaveButton",
  enterServerDetails: "enterServerDetails",
  setCookiePathFromDialog: "setCookiePathFromDialog",
  useCookieAuthentication: "useCookieAuthentication",
  rpcSettingsFromCookiePath: "rpcSettingsFromCookiePath",
  rpcSettingsFormUsername: "rpcSettingsFormUsername",
  rpcSettingsFormPassword: "rpcSettingsFormPassword",
  rpcSettingsFormServerUrl: "rpcSettingsFormServerUrl",
  connectionStatusReportCloseButton: "connectionStatusReportCloseButton",
  useDefaultSettings: "useDefaultSettings",
  blockListBlock: "blockListBlock",
  scrollableBlockContainer: "scrollableBlockContainer",
  settingsPage: "settingsPage",
  settingsButton: "settingsButton",
  settingsSavedSnackBar: "settingsSavedSnackBar",
  homeButton: "homeButton",
  explorerPage: "explorerPage",
  transactionDetails: "transactionDetails",
  depthTopLink: "depthTopLink",
  blockDetails: "blockDetails",
  blockDetailsH1: "blockDetailsH1",
} as const);
